# Generated by Django 2.0.6 on 2018-07-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20180706_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.Coin'),
        ),
    ]
