# Generated by Django 2.0.6 on 2018-06-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulating_supply', models.FloatField(default=-1)),
                ('name', models.CharField(default='', max_length=20)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('API_ID', models.IntegerField(default=-1)),
                ('price', models.FloatField(default=-1)),
                ('last_updated', models.FloatField(default=-1)),
                ('market_cap', models.FloatField(default=-1)),
                ('volume', models.FloatField(default=-1)),
            ],
        ),
    ]
