# Generated by Django 2.0.6 on 2018-07-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('circulating_supply', models.FloatField(blank=True, default=-1, null=True)),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('symbol', models.CharField(default='', max_length=100, unique=True)),
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, default=-1, null=True)),
                ('last_updated', models.FloatField(blank=True, default=-1, null=True)),
                ('marketcap', models.FloatField(blank=True, default=-1, null=True)),
                ('volume', models.FloatField(blank=True, default=-1, null=True)),
                ('slug', models.SlugField(default='')),
                ('rank', models.IntegerField(blank=True, default=-1, null=True)),
                ('percent_change_24h', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
