# Generated by Django 2.0.6 on 2018-06-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='API_ID',
        ),
        migrations.AddField(
            model_name='coin',
            name='rank',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='coin',
            name='slug',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
