# Generated by Django 2.0.6 on 2018-06-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20180610_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='market_cap',
            new_name='marketcap',
        ),
        migrations.AddField(
            model_name='coin',
            name='percent_change_24h',
            field=models.FloatField(default=0),
        ),
    ]
