# Generated by Django 2.0.6 on 2018-06-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20180611_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='circulating_supply',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_updated',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='marketcap',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='percent_change_24h',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='rank',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
